OpenLayers.Lang.be = OpenLayers.Util.extend(OpenLayers.Lang.be, {
    "Please zoom in to be able to select features": "Калі ласка, павялічце мапу, каб пачаць рэдагаванне",
    "Dismiss": "Схаваць",
    "You have unsaved changes. If you proceed, these changes will be lost": "Вашыя змены яшчэ не захаваныя. Калі Вы працягнеце, яны будуць згубленыя",
    "Discard changes": "Скасаваць змены",
    "Timed out waiting for data to load.": "Таймаўт",
    "Features": "Звесткі",
    "Loading data": "Загрузка звестак",
    "Opening the new changeset": "Адкрыццё пакета зменаў",
    "Log": "Журнал працы",
    "Use Ctrl+drag to select the area to download. Remember that you have to be a <a href='https://www.openstreetmap.org/user/new'>registered</a> OpenStreetMap user to save your changes.": "Вылучце проставугольную вобласць, заціснуўшы Ctrl. Памятайце, для захавання зменаў неабходна быць <a href='https://www.openstreetmap.org/user/new'>зарэгістраваным</a> карыстальнікам OpenStreetMap.",
    "Tags to edit (click to change)": "Тэгі для рэдагавання (націсніце, каб змяніць)",
    "Are you sure?": "Упэўненыя?",
    "Downloading": "Загрузка звестак",
    "Uploading changes": "Захаванне звестак",
    "Closing the changeset": "Закрыццё пакета зменаў",
    "Ctrl-Drag to select the area to translate.<br />This tool is still a work-in-progress. Please <a href='https://bitbucket.org/andrew_shadoura/online-translator/issues/new'>report</a> any bugs you find to the author.": "Вылучце вобласць з Ctrl.<br />Гэты інструмент знаходзіцца ў распрацоўцы. <a href='https://bitbucket.org/andrew_shadoura/online-translator/issues/new'>Паведамляйце</a> пра памылкі аўтарам.",
    "done": "зроблена",
    "failure": "памылка",
    "success": "скончана паспяхова",
    "permalink": "Сталая спасылка",
    "Permalink": "Сталая спасылка",
    "Make default": "Зрабіць асноўным",
    "User name": "Вашае імя",
    "Password": "Пароль",
    "Let me in": "Увайсці",
    "Logged in successfully.": "Увайшлі паспяхова",
    "Failed to log in.": "Памылка, праверце імя і пароль",
    "You haven't yet logged in.": "Вы яшчэ не ўвайшлі ў сістэму",
    "Log in": "Прадстаўцеся",
    "or": "ці",
    "Register": "Зарэгіструйцеся",
    "Load anyway": "Загрузіць усё роўна",
    "Zoom": "Наблізіць"
});

OpenLayers.Lang.ru = OpenLayers.Util.extend(OpenLayers.Lang.ru, {
    "Please zoom in to be able to select features": "Пожалуйста, приблизьте карту, чтобы начать редактирование",
    "Dismiss": "Закрыть",
    "You have unsaved changes. If you proceed, these changes will be lost": "Ваши изменения ещё не сохранены. Если Вы продолжите, они будут утеряны",
    "Discard changes": "Отменить правки",
    "Timed out waiting for data to load.": "Таймаут",
    "Features": "Данные",
    "Loading data": "Загрузка данных",
    "Opening the new changeset": "Открытие пакета правок",
    "Log": "Журнал работы",
    "Use Ctrl+drag to select the area to download. Remember that you have to be a <a href='https://www.openstreetmap.org/user/new'>registered</a> OpenStreetMap user to save your changes.": "Выделите прямоугольную область, зажав Ctrl. Учтите, для сохранения правок необходимо быть <a href='https://www.openstreetmap.org/user/new'>зарегистрированным</a> пользователем OpenStreetMap.",
    "Tags to edit (click to change)": "Теги для редактирования (нажмите, чтобы изменить)",
    "Are you sure?": "Уверены?",
    "Downloading": "Загрузка данных",
    "Uploading changes": "Сохранение данных",
    "Closing the changeset": "Закрытие пакета правок",
    "Ctrl-Drag to select the area to translate.<br />This tool is still a work-in-progress. Please <a href='https://bitbucket.org/andrew_shadoura/online-translator/issues/new'>report</a> any bugs you find to the author.": "Выделите область с Ctrl.<br />Этот инструмент находится в разработке. <a href='https://bitbucket.org/andrew_shadoura/online-translator/issues/new'>Сообщайте</a> об ошибках авторам.",
    "done": "завершено",
    "failure": "ошибка",
    "success": "завершено успешно",
    "Say": "Сообщить",
    "Your message:": "Комментарий",
    "Bump": "Спящий полицейский",
    "Load anyway": "Загрузить всё равно",
    "Speedcam": "Камера",
    "Type:": "Вид:",
    "Your name:": "Представьтесь:",
    "NoName": "Кто-то",
    "Please fill in your name": "Представьтесь, пожалуйста",
    "Comment is required": "Впишите, пожалуйста, комментарий",
    "Something's wrong": "Ошибка на карте",
    "Description": "Описание",
    "Comment": "Комментарий",
    "Permalink": "Постоянная ссылка",
    "permalink": "Постоянная ссылка",
    "User name": "Ваше имя",
    "Password": "Пароль",
    "Let me in": "Войти",
    "Logged in successfully.": "Вошли успешно",
    "Failed to log in.": "Ошибка, проверьте имя и пароль",
    "You haven't yet logged in.": "Вы ещё не вошли в систему",
    "Log in": "Представьтесь",
    "or": "или",
    "Register": "Зарегистрируйтесь",
    "Zoom": "Приблизить",
    "Unresolved Error": "Неисправленная неточность",
    "Comment/Close": "Изменить",
    "Traffic Calming": "",
    "Nickname": "Представьтесь",
    "Make default": "Сделать основным",
    "New bumps can be added on zoom level 17 or greater<br/>More info can be found <a href='http://blog.latlon.org/2010/11/16/otmetki-o-lezhachikh-policejjskikh-v-osm/'>here</a>": "Добавлять сведения можно только на максимальном уровне детализации<br/>Подробности <a href='http://blog.latlon.org/2010/11/16/otmetki-o-lezhachikh-policejjskikh-v-osm/'>здесь</a>"
});

